version: "3.7"
services:
    app:
        build:
            args:
                user: moatmusic
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        container_name: moatmusic-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - moatmusic-net

    db:
        image: mysql:5.7
        container_name: moatmusic-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - moatmusic-net

    nginx:
        image: nginx:latest
        container_name: moatmusic-nginx
        restart: unless-stopped
        ports:
            - 5000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - moatmusic-net

networks:
    moatmusic-net:
        driver: bridge
